
--DROP DATABASE IF EXISTS mydb;
--CREATE DATABASE mydb;
--\c mydb;
DROP TABLE IF EXISTS test_table;
CREATE TABLE test_table (id integer, name text);
INSERT INTO test_table VALUES (1, 'hello database');
INSERT INTO test_table VALUES (2, 'goodbye database');

DROP TABLE IF EXISTS users;
create table users (
  id int generated by default as identity not null,
  email varchar(100) null,
  googleid varchar(100) null,
  primary key (id)
);

INSERT INTO users(email, googleid) VALUES ('a@uci.edu', '69420');
